apiVersion: v1
kind: Service
metadata:
  name: {{ include "arqh.componentName" (dict "root" . "name" "api") }}
  labels:
    {{- include "arqh.commonLabels" (dict "root" . "name" "api" "component" "backend") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "arqh.selectorLabels" (dict "root" . "name" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
