apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arqh.componentName" (dict "root" . "name" "secrets") }}
  labels:
    {{- include "arqh.commonLabels" (dict "root" . "name" "secrets" "component" "backend") | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | quote }}
  REDIS_USERNAME: {{ .Values.secrets.REDIS_USERNAME | quote }}
  MONGO_USERNAME: {{ .Values.secrets.MONGO_USERNAME | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.MONGO_PASSWORD | quote }}
