apiVersion: v1
kind: Service
metadata:
  name: {{ include "dispatch.componentName" (dict "root" . "name" "web") }}
  labels:
    {{- include "dispatch.commonLabels" (dict "root" . "name" "web" "component" "proxy") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "dispatch.selectorLabels" (dict "root" . "name" "web") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
